### ISSUE TITLE
New Command: dump_stats

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/DebugToolkit#102]
**Describe your new command**
Dump all stats of the current characterbody in the console

**Use cases**
Wiki work, creating a new character

**Comment by SChinchi** [comment]
How do you envision that working? It could be the base stats, e.g.,

```
health: baseHealth (+levelHeath)
regen: baseRegen (+levelRegen)
shield: etc
```

in which case it could use the body of the player (or any other player/pinged entity), or straight up any body prefab.

Or it could be the current stats, e.g,

```
health: currentHealth / maxHealth (+regen)
jumps: currentJumpCount / maxJumpCount
```

in which case we can also list the `current/max stock (currentCooldown / maxCooldown)` for the primary, secondary, etc. We can even go as far as mentioning the current skillDriver/entityState.

Or maybe we call the latter `dump_state`.

---
On a similar note, I also have a couple of commands, `dump_inventories`, and `dump_buffs`, which list the inventory/buffs for all the bodies on the stage. I've found them useful countless number of times, from debugging when a custom buff implementation goes to negative stacks, to keeping track what items I've given to what entity, or discovering what untiered items enemies get.

I can add them in along with implementing `dump_stats`. Maybe we even get a family of `dump_` commands going.
