### ISSUE TITLE
Change Command: <spawn_ai>

### ISSUE THREAD

**Issue by Lyefyre** [harbingerofme/DebugToolkit#104]
**Which Command**
spawn_ai

**What should it do?**
The command is good as is, but could be extended with more parameters, to make it more versatile.

1. Provide an option, that determines whether the spawned entity teleports with the player, after the player leaves the stage (Like gunner drones and turrets)
2. Provide an option that determines, whether the spawned entity follows the player (like gunner and healing drones).
3. Provide an option that when spawned, the entity copies the player's current inventory (like engineer turrets)

**Use cases:**
1. Better labbing. Specifically for certain damage testing.
2. Creation of fun, custom game modes with friends.

for further questions, ask Lye#9506 or my friend Violet Chaolan, who will relay it to me.

**Comment by harbingerofme** [comment]
Spawn ai is already very big. Maybe `spawn_follower` ?

**Comment by Lyefyre** [comment]
Theoretically, you could split the command into spawn_ai and spawn_ally, but keeping all of those options would have advantages to keep that functionality to enemies aswell:

1. Imagine you want to make a challenge run: You spawn an unkillable enemy that harasses you constantly, but you can't get rid of it because it teleports with you.
2. Enemies with items could also make for some obvious jank and "arena" style gamemodes, where you pitch monsters against each other.
3. In a pvp based gamemode, you need to separate the 2 players that are fighting eachother into 2 teams, those teams are currently labelled as "Friends" and "Monsters" I believe. By having those options available to "monsters" aswell, each could choose a personal bodyguard for example.

I understand that the practical applications of my suggestions are somewhat niche. I've been using debugtoolkit a lot to play around with various settings. I also understand that spawn_ai as is would be bloated with parameters, but it's a powerful command and in my eyes, one of the most important ones. Maybe some of the things I suggested are not even technically feasible, like the following thing? Please let me know and thank you for your time.

**Comment by xiaoxiao921** [comment]
These commands options are feasible, but I don't really see how these relates to the mod original purpose

**Comment by Lyefyre** [comment]
Hey guys, thanks for the discussion, in here and in Discord. It's clear that my requests go beyond the intended scope of this mod. While I would be happy for these to be integrated in any way you see fit, I have nothing more to add and will close this issue.
