### ISSUE TITLE
Recommend KingEnderBrine's midrunartifacts in readme

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/DebugToolkit#105]
~~**Describe your new command**~~
~~Toggle the state of an artifact mid run. Probably harder than it looks.~~

~~**Use cases**~~
~~Testing things under different circumstances.~~

Add recomendation to @KingEnderBrine's midrunartifacts in readme

**Comment by DestroyedClone** [comment]
Package by KingEnderBrine has this functionality, so it can possibly be mirrored or asked for integration, or recommended as a download for the next package release (whenever that may be).
[Github](https://github.com/KingEnderBrine/-RoR2-MidRunArtifacts) + [Thunderstore](https://thunderstore.io/package/KingEnderBrine/MidRunArtifacts/)
