### ISSUE TITLE
Change Command: teleport_on_cursor

### ISSUE THREAD

**Issue by paddywaan** [harbingerofme/DebugToolkit#107]
**Which Command**
`teleport_on_cursor`

**What should it do?**
teleport_on_cursor should follow the syntax: teleport_on_cursor {self (default) | currentPlayerSpectated | specific player} {cursor(default) | specific player}

The default behaviour of teleporting self onto cursor would remain consistent, but the new parameters should be integrated to allow for more flexible usage. Similarly, if the player who is executing the command is not alive, the error: `This command only works when in a Run !` is produced, which is incorrect.

**Comment by xiaoxiao921** [comment]
Players are authoritative of their own transform, for that to work they would need to answer a rpc call, meaning they need the mod. I don't see a use case for this except trolling ?

**Comment by paddywaan** [comment]
Hmm, yeah I see how that can be problematic, however with mod sync being enforced between clients, at least for my usecase this doesn't appear to be an issue. The case for this isn't really related to debugging but rather to game play, where players find themselves in unfortunate circumstances due to vanilla bugs (abyssal depths gates closed for clients but not host) and the like.

However, if all players use this mod, they can also execute the command themselves which negates the context of this feature request somewhat.

**Comment by xiaoxiao921** [comment]
Debugtoolkit isnt required by everyone, stated by this line 
https://github.com/harbingerofme/DebugToolkit/blob/master/Code/DebugToolkit.cs#L16
The case you describe cannot work because of what I said earlier, player transform are authoritative of their own transform, so they need the mod
