### ISSUE TITLE
[BUG] 'cheats' is not enabled for 'set_scene'

### ISSUE THREAD

**Issue by DestroyedClone** [harbingerofme/DebugToolkit#115]
**Describe the bug**
Before SOTV, DebugToolkit would automatically enable the convar 'cheats' (or rather maybe it overrode it to make the game think it was enabled) which allowed access to some base game commands. Now, I'm getting an issue where I can't use `set_scene` because cheats aren't enabled.
![image](https://user-images.githubusercontent.com/72328339/157353896-9713af83-4d26-4f2d-a2da-72a21a9f3e51.png)

**Does the bug happen without input**
No

**If input is required, which scenes does it go wrong in**
Tested in run

**Do you have other mods installed?**
A modlist would be most helpful for spotting conflicts. You do not have to mention R2API and bepinex.
![image](https://user-images.githubusercontent.com/72328339/157353970-7ed1cfad-6896-4c44-9b99-6cdcd15a581b.png)

**Comment by harbingerofme** [comment]
This is fixed in 3.7.1
