### ISSUE TITLE
[BUG] "cheats" isn't working

### ISSUE THREAD

**Issue by Mishakak** [harbingerofme/DebugToolkit#118]
**Describe the bug**
![Новый точечный рисунок](https://user-images.githubusercontent.com/102033527/159258793-0d693eeb-9f16-4bb3-9cd9-ba8afc522887.jpg)
In SOTV cheats can't be changed to 1

**Does the bug happen without input**
no

**If input is required, which scenes does it go wrong in**
all of them

**Do you have other mods installed?**
BetterUI

**Comment by harbingerofme** [comment]
The cheats convar should not be needed to set.
Use `time_scale` instead of timescale.
