### ISSUE TITLE
New Command: log_trace

### ISSUE THREAD

**Issue by MightyW0lf** [harbingerofme/DebugToolkit#121]
**Describe your new command**
Simply prints something to the log output (probably current time and perhaps some counter?).

**Use cases**
It can be used to mark a specific place in log output so it can be referenced later when debugging. Especially useful when bound to a hotkey. Or even better when bound to the same key as a replay buffer - then you can see where in the log output you saved each replay.

Currently this behavior can be to some extent simulated with `add_money 0` command, which prints `$$$`.

**Comment by SChinchi** [comment]
Shouldn't this be closed because `echo` achieves exactly that?
