### ISSUE TITLE
[BUG] Missing interactables

### ISSUE THREAD

**Issue by DestroyedClone** [harbingerofme/DebugToolkit#125]
**Describe the bug**
`list_interactables` and `spawn_interactible` are missing interactables, only showing ~27.
```
[Info: Unity Log] Chest1
Chest2
EquipmentBarrel
TripleShop
LunarChest
CategoryChestDamage
CategoryChestHealing
CategoryChestUtility
CategoryChest2Damage
Barrel1
ShrineBloodSnowy
ShrineBossSnowy
ShrineChanceSnowy
BrokenDrone1
BrokenDrone2
BrokenTurret1
Chest1Stealthed
RadarTower
ShrineGoldshoresAccess
GoldChest
Duplicator
DuplicatorLarge
DuplicatorMilitary
DuplicatorWild
Scrapper
VoidChest
VoidCamp
```

According to LegacyResourcesAPI, there should be about 57 listed.

**Does the bug happen without input**
No

**If input is required, which scenes does it go wrong in**
All of them

**Do you have other mods installed?**
Runtimeinspector

**Comment by xiaoxiao921** [comment]
Should be fixed
