### ISSUE TITLE
Improve the location of spawning commands

### ISSUE THREAD

**Issue by SChinchi** [harbingerofme/DebugToolkit#140]
`spawn_interactable`
--

Issues:
* It uses the body's center of mass position, so interactables are floating a bit over the ground. For interactables with collision, such as adaptive chests, this can cause the players to be stuck without mobility skills (I've managed to escape with wiggling before, but still).
* It currently uses `SpawnCard.DoSpawn`, so the `DirectorSpawnRequest` is ignored, including `preventOverhead`.

Solution:
* Use `CharacterBody.footPosition` instead.
* Make the spawn via `DirectorCore` with `PlacementRule.Direct`.  `PlacementRule.NearestNode` is another approach, but if the player is far away from any nodes, e.g., Scorched Acres on the secret area, the spawn will be too far away. We could have a fallback with a direct spawn in that case, but that's basically the suggested solution with more steps. NearestNode also gives less agency where the interactable will be spawned.

`spawn_ai`
--

Issues:
* It also uses the body's center of mass position, but that is less of an issue. However, since it uses the same position for each spawn, it can cause flyers to be pushed far away, causing some to either hit OOB, or be so far away from any nodes that they can't move.

Solution:
* I'm undecided so far.
    * Making use of the nodes can provide a clean solution for both flyers and ground enemies and without swarming the player. The issue is with being too far away from any nodes, in which case the spawn(s) will fail. This may not be an issue anyway, since enemies without access to nodes seem to just do nothing.
    * Use direct spawns. Maybe even something like spawning multiple enemies around a circle with a fixed distance from the player. This seems reasonable in an open field, but near a wall or a cliff for ground enemies the result will be undesirable.

Addendum
--
We can make all commands work from a DS if we add an extra target argument which defaults to the command sender.

**Comment by xiaoxiao921** [comment]
Honestly this sound like a non issue if you have noclip enabled, no?

**Comment by SChinchi** [comment]
That's a fair point, I forgot about that. The issue with the floating interactables is mainly that they look a bit off, but I'll admit that isn't a big issue either.
