### ISSUE TITLE
[BUG] Non-US Keyboard Keybind

### ISSUE THREAD

**Issue by itsPoipoi** [harbingerofme/DebugToolkit#180]
Please provide the option to change the keybind to open console. The mentioned mod in the description is deprecated and doesn't work anymore. This means having to toggle on a US keyboard layout currently to open console.

**Comment by harbingerofme** [comment]
Hey, we've compiled a list of the keys for other layouts. See if yoyur layout is in the list, and if it isn't, uh, keymash until you find it and let me know so I can expand it.
If the default hotkey combination doesn't work for you, please see if your keyboard layout is in this list.
DEU: ctrl+alt+Ö
ESP: ctrl+alt+ñ
FIN: ctrl+alt+Ō
FRA: ctrl+alt+ù
NOR: ctrl+alt+ø
PRT: ctrl+alt+ç
USA: ctrl+alt+`

**Comment by itsPoipoi** [comment]
Hey, thanks for your quick response. Works for my FRA. I suggest you add the list to the mod description so you won't have to waste your time with this. Thanks again :)
