### ISSUE TITLE
New name for project

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/DebugToolkit#43]
We are looking for a new name for the project.
Use 👍 on comments on this issue to promote names that have your fancy.

**Comment by harbingerofme** [comment]
ConsoleCommands

**Comment by harbingerofme** [comment]
DebugToolkit

**Comment by harbingerofme** [comment]
TestingPackage

**Comment by harbingerofme** [comment]
TestingToolkit

**Comment by harbingerofme** [comment]
TestToolkit

**Comment by harbingerofme** [comment]
DebugMenu

**Comment by harbingerofme** [comment]
DevelopmentDebugSuite

**Comment by harbingerofme** [comment]
ConsolePlusPlus

**Comment by SushiDevshi** [comment]
CBT
C -Carbon
B - Burst 
T - Tester
This clearly relates to Risk of Rain 2, because carbon is in water, and rain is water, burst because rain comes down in short bursts, tester because it's a mod that helps mod devs test their mods.

**Comment by mistername** [comment]
DebugPlusPlus

**Comment by Paddywaan** [comment]
DebugToolkit Winner Winner Chicken Dinner!

**Comment by harbingerofme** [comment]
I'm still working out how to properly transition on thunderstore.

**Comment by Paddywaan** [comment]
Perhaps we stub RoR2Cheats3.0 with a null plugin and then depend upon DebugToolkit in order to "remove" prior versions, maintain interoperability, and encourage transition from old to new? Does anyone see an issue with this occuring?

**Comment by harbingerofme** [comment]
The `BepinIncompatibility ` will take care of this.

**Comment by harbingerofme** [comment]
Closed again in dd2260c59b0ea040e4ce6c0c9d2306b4c0d1c6cb
