### ISSUE TITLE
Change Command: <set_scene>

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/DebugToolkit#55]
**Which Command**
vanilla `set_scene`

**What should it do?**
It currently checks for cheats inside the method. We can fix this with the power of IL (or On. += cheats=true;orig(self,args);cheats=false)
Continues #23

**Comment by Paddywaan** [comment]
set scene? isn't this just a wider version of next_stage which applies to all scenes including menus? Infact, i'm pretty sure that next_stage will also set the scene to a menu too. I'm not sure that a difference exists.

**Comment by harbingerofme** [comment]
```csharp 
   [ConCommand(commandName = "set_scene", flags = ConVarFlags.None, helpText = "Changes to the named scene.")]
    private static void CCSetScene(ConCommandArgs args)
    {
      args.CheckArgumentCount(1);
      if ((RoR2Application.cvCheats.boolValue ? 1 : 0) == 0 & (!(bool) ((UnityEngine.Object) GameNetworkManager.singleton) || GameNetworkManager.singleton.isNetworkActive) && Array.IndexOf<string>(GameNetworkManager.sceneWhiteList, args[0]) == -1)
        return;
      if (!(bool) ((UnityEngine.Object) GameNetworkManager.singleton))
        throw new ConCommandException("set_scene failed: GameNetworkManager is not available.");
      if (NetworkServer.active)
      {
        Debug.LogFormat("Setting server scene to {0}", (object) args[0]);
        GameNetworkManager.singleton.ServerChangeScene(args[0]);
      }
      else
      {
        if (NetworkClient.active)
          throw new ConCommandException("Cannot change scene while connected to a remote server.");
        Debug.LogFormat("Setting offline scene to {0}", (object) args[0]);
        SceneManager.LoadScene(args[0], LoadSceneMode.Single);
      }
    }
``` 
For reference

**Comment by harbingerofme** [comment]
We use the scenecatalog and run,instance.advanceStage to change the stage, while this is managed by the scenemanager/gamenetworkmanager. 
May be that different roads lead to rome.

**Comment by Paddywaan** [comment]
If behaviour is the same we should just defer to vanilla. If we want to maintain interop for current developers we can just parse arguments by proxy
