### ISSUE TITLE
[BUG] noclip does not properly maintain through stage transition

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/DebugToolkit#64]
**Describe the bug**
After using `noclip` and using `next_stage`, noclip flight is still enabled horizontally. gravity is slowed to a crawl, and collision with the stage happens agains.

**Does the bug happen without input**
No

**If input is required, which scenes does it go wrong in**
ingame

**Do you have other mods installed?**
Bleeding Edge HarbTweaks with no hooks enabled.

**Comment by xiaoxiao921** [comment]
fixed in #65
