### ISSUE TITLE
[BUG] fixed_time does not use ingame timed, but rather unpauzed time

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/DebugToolkit#89]
**Describe the bug**
When requesting the time, the unpaused time is given. This is probably indication it might not set the right time either.

**Does the bug happen without input**
no

**If input is required, which scenes does it go wrong in**
ingame

**Comment by SuperRayss** [comment]
RoR2.Run GetRunStopwatch() utilizes an offset for stages where the timer was paused. Try using that instead of Run.instance.fixedTime

**Comment by harbingerofme** [comment]
fixed in #91
