### ISSUE TITLE
[BUG] spawn_ai always spawns blazing enemies

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/DebugToolkit#90]
**Describe the bug**
when using spawn_ai, no matter what elitetype is given, even none, a blazing enemy will be spawned.

**Does the bug happen without input**
No

**If input is required, which scenes does it go wrong in**
ingame

**Comment by SushiDevshi** [comment]
i'm tired of burning to death because of blazing beetles, harb.

**Comment by harbingerofme** [comment]
Currently the system works, except the elite index for fire is 0. which is potentially confusing. Do we decrease the index by one if a number is given as argument?

**Comment by harbingerofme** [comment]
Underlying issue with the enum parser not being able to handle negative numbers is now solved. Closing the issue
