### ISSUE TITLE
[BUG] obliteration while noclipping breaks pregame lobby

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/DebugToolkit#92]
**Describe the bug**
After obliterating with noclip enabled, the pregame lobby does not let you exit to the main menu.
[LogOutput.log](https://github.com/harbingerofme/DebugToolkit/files/4284324/LogOutput.log)

**Does the bug happen without input**
No

**If input is required, which scenes does it go wrong in**
pregame lobby/ingame

**Do you have other mods installed?**
A few

**Comment by xiaoxiao921** [comment]
should be fixed in https://github.com/harbingerofme/DebugToolkit/commit/43833206bfecb99eee7256049c4384f0b1ea110b
