### ISSUE TITLE
Invalid Cast Exception when using give_item and remove_item

### ISSUE THREAD

**Issue by freezebomber** [harbingerofme/DebugToolkit#96]
**Which Command**
give_item and remove_item

**What should it do?**
when ever I try to use the command I get InvalidCastException: Specified cast is not valid.
ps sorry if this should be in bug report

**Comment by harbingerofme** [comment]
Please make sure you are on the latest R2API. If you are, can you please upload your logoutput.log file? It's located in your bepinex folder.

**Comment by freezebomber** [comment]
thank you after updating to the newest R2API it works great

**Comment by harbingerofme** [comment]
Glad to hear that.
