### ISSUE TITLE
New Command: Give_buff + remove_buff

### ISSUE THREAD

**Issue by harbingerofme** [harbingerofme/DebugToolkit#98]
**Describe your new command**
* `give_buff {buffname/index} [player:default=self] [time:default=None]`
 Adds the specified buff to the target player, permanently or optionally timed with the time parameter.
* `remove_buff {buffName/index/'all'} [player:default=self]`
 Removes the specified buff (or all) from the specified buff from the target player.

**Use cases**
Testing custom buffs. Can additionally be used to permanently give the OnFire debuff to set regen to 0 quickly.

**Comment by DestroyedClone** [comment]
Shouldn't this be closed due to https://github.com/harbingerofme/DebugToolkit/commit/aa83d6acef135215cf6dd7d42d7ac202ab495d1e ?
